/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FirstComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SecondComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TranslatedComponent {
    }
}
declare global {
    interface HTMLFirstComponentElement extends Components.FirstComponent, HTMLStencilElement {
    }
    var HTMLFirstComponentElement: {
        prototype: HTMLFirstComponentElement;
        new (): HTMLFirstComponentElement;
    };
    interface HTMLSecondComponentElement extends Components.SecondComponent, HTMLStencilElement {
    }
    var HTMLSecondComponentElement: {
        prototype: HTMLSecondComponentElement;
        new (): HTMLSecondComponentElement;
    };
    interface HTMLTranslatedComponentElement extends Components.TranslatedComponent, HTMLStencilElement {
    }
    var HTMLTranslatedComponentElement: {
        prototype: HTMLTranslatedComponentElement;
        new (): HTMLTranslatedComponentElement;
    };
    interface HTMLElementTagNameMap {
        "first-component": HTMLFirstComponentElement;
        "second-component": HTMLSecondComponentElement;
        "translated-component": HTMLTranslatedComponentElement;
    }
}
declare namespace LocalJSX {
    interface FirstComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SecondComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TranslatedComponent {
    }
    interface IntrinsicElements {
        "first-component": FirstComponent;
        "second-component": SecondComponent;
        "translated-component": TranslatedComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "first-component": LocalJSX.FirstComponent & JSXBase.HTMLAttributes<HTMLFirstComponentElement>;
            "second-component": LocalJSX.SecondComponent & JSXBase.HTMLAttributes<HTMLSecondComponentElement>;
            "translated-component": LocalJSX.TranslatedComponent & JSXBase.HTMLAttributes<HTMLTranslatedComponentElement>;
        }
    }
}
